import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { ChatProvider } from "@/context/ChatProvider";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  axios.defaults.withCredentials = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChatProvider>
        
        {children}
      <Toaster />
      </ChatProvider>
      </body>
    </html>
  );
}
